name: Build Release APK

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version name (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build-release:
    name: Build Release APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Update version in build.gradle.kts
        run: |
          sed -i "s/versionName = \".*\"/versionName = \"${{ github.event.inputs.version_name }}\"/" app/build.gradle.kts
      
      - name: Build Release APK
        run: ./gradlew assembleRelease
      
      - name: Sign APK (optional - requires keystore setup)
        run: echo "APK signing skipped. Configure keystore in repository secrets for signed builds."
      
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: mytracker-release-${{ github.event.inputs.version_name }}
          path: app/build/outputs/apk/release/app-release-unsigned.apk
      
      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version_name }}
          name: Release ${{ github.event.inputs.version_name }}
          draft: true
          files: app/build/outputs/apk/release/app-release-unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

